import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { lexiconSchema, type CanonicalWeaponType } from './schema.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '../../..');
const LEXICON_PATH = path.join(REPO_ROOT, 'alert_lexicon.json');
const GENERATED_DIR = path.resolve(__dirname, '../generated');

const MIN_CONFIDENCE = 0.7;
const MIN_CONFIDENCE_ALLOWLIST = new Set([
  's300',
  'v2u',
  'herbera',
  'Лозова',
  'Малинівка (Чугуївський р-н)',
  'Малинівка (Дергачівський р-н)',
]);
const SUPPORTED_CANONICAL_WEAPONS = new Set<CanonicalWeaponType>([
  'shahed',
  'bpla',
  's300',
  'kab',
  'iskander',
  'missile',
  'unknown',
  'fpv',
  'molniya',
  'lancet',
  'ballistic',
  'rszo',
]);

function normalizeAlias(input: string): string {
  return input.toLowerCase().replace(/\s+/g, ' ').trim();
}

function sortedUnique(values: string[]): string[] {
  const byNormalized = new Map<string, string>();
  for (const value of values.map((v) => v.trim()).filter(Boolean)) {
    const key = normalizeAlias(value);
    if (!byNormalized.has(key)) {
      byNormalized.set(key, value);
    }
  }
  return [...byNormalized.values()].sort((a, b) => a.localeCompare(b, 'uk'));
}

function toTsConst(name: string, value: unknown): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

async function writeGeneratedFile(fileName: string, body: string): Promise<void> {
  const content = `/* eslint-disable */
// This file is auto-generated by src/lexicon/generate.ts.
// Do not edit manually.

${body}`;
  await writeFile(path.join(GENERATED_DIR, fileName), content, 'utf8');
}

async function run(): Promise<void> {
  const raw = await readFile(LEXICON_PATH, 'utf8');
  const lexicon = lexiconSchema.parse(JSON.parse(raw));
  await mkdir(GENERATED_DIR, { recursive: true });

  const validationErrors: string[] = [];
  const warnings: string[] = [];
  const ambiguousPriorityByTerm = new Map(
    lexicon.top_ambiguous_terms.map((term) => [normalizeAlias(term.term), term.priority]),
  );

  // Confidence gate.
  for (const entry of [...lexicon.location_dictionary, ...lexicon.weapon_dictionary]) {
    if (entry.confidence < MIN_CONFIDENCE && !MIN_CONFIDENCE_ALLOWLIST.has(entry.canonical)) {
      validationErrors.push(
        `Confidence ${entry.confidence.toFixed(2)} is below ${MIN_CONFIDENCE.toFixed(2)} for "${entry.canonical}"`,
      );
    }
  }

  // Build location aliases keyed by canonical.
  const generatedLocationAliases: Record<string, string[]> = {};
  const locationAliasMap = new Map<string, { canonical: string; confidence: number }>();
  for (const item of lexicon.location_dictionary) {
    const canonical = item.canonical.trim();
    if (!generatedLocationAliases[canonical]) generatedLocationAliases[canonical] = [];
    generatedLocationAliases[canonical].push(canonical, ...item.aliases);
  }
  for (const canonical of Object.keys(generatedLocationAliases)) {
    generatedLocationAliases[canonical] = sortedUnique(generatedLocationAliases[canonical]);
    for (const alias of generatedLocationAliases[canonical]) {
      const normalized = normalizeAlias(alias);
      const existing = locationAliasMap.get(normalized);
      if (!existing) {
        const confidence =
          lexicon.location_dictionary.find((x) => x.canonical === canonical)?.confidence ?? 1;
        locationAliasMap.set(normalized, { canonical, confidence });
        continue;
      }
      if (existing.canonical !== canonical) {
        const message = `Location alias collision "${alias}" between "${existing.canonical}" and "${canonical}"`;
        const ambiguousPriority = ambiguousPriorityByTerm.get(normalized);
        if (ambiguousPriority) {
          warnings.push(`${message} (ambiguous term priority=${ambiguousPriority})`);
        } else if (
          Math.max(
            existing.confidence,
            lexicon.location_dictionary.find((x) => x.canonical === canonical)?.confidence ?? 1,
          ) >= 0.9
        ) {
          validationErrors.push(message);
        } else {
          warnings.push(message);
        }
      }
    }
  }

  // Build weapon alias map from supported canonicals.
  const generatedWeaponAliases: Record<CanonicalWeaponType, string[]> = {
    shahed: [],
    bpla: [],
    s300: [],
    kab: [],
    iskander: [],
    missile: [],
    unknown: [],
    fpv: [],
    molniya: [],
    lancet: [],
    ballistic: [],
    rszo: [],
  };
  const weaponAliasMap = new Map<string, CanonicalWeaponType>();
  for (const item of lexicon.weapon_dictionary) {
    if (!SUPPORTED_CANONICAL_WEAPONS.has(item.canonical as CanonicalWeaponType)) {
      warnings.push(`Skipping unsupported weapon canonical "${item.canonical}"`);
      continue;
    }
    const canonical = item.canonical as CanonicalWeaponType;
    const candidates = sortedUnique([canonical, ...item.aliases]);
    generatedWeaponAliases[canonical].push(...candidates);
    for (const alias of candidates) {
      const normalized = normalizeAlias(alias);
      const existing = weaponAliasMap.get(normalized);
      if (!existing) {
        weaponAliasMap.set(normalized, canonical);
        continue;
      }
      if (existing !== canonical) {
        validationErrors.push(
          `Weapon alias collision "${alias}" between "${existing}" and "${canonical}"`,
        );
      }
    }
  }
  for (const key of Object.keys(generatedWeaponAliases) as CanonicalWeaponType[]) {
    generatedWeaponAliases[key] = sortedUnique(generatedWeaponAliases[key]);
  }

  const phraseIntents = lexicon.phrase_patterns.map((p) => ({
    intent: p.intent,
    regex: p.regex,
  }));
  const ambiguousTerms = lexicon.top_ambiguous_terms.map((term) => ({
    term: term.term,
    possibleMappings: term.possible_mappings,
    priority: term.priority,
  }));
  const priorityHotspots = lexicon.priority_hotspots
    .slice()
    .sort((a, b) => a.priority_rank - b.priority_rank)
    .map((x) => x.canonical);

  for (const term of ambiguousTerms) {
    const unresolved = term.possibleMappings.filter((m) => !generatedLocationAliases[m]);
    if (unresolved.length > 0) {
      warnings.push(
        `Ambiguous term "${term.term}" maps to unknown canonical(s): ${unresolved.join(', ')}`,
      );
    }
  }

  if (validationErrors.length > 0) {
    throw new Error(`Lexicon validation failed:\n- ${validationErrors.join('\n- ')}`);
  }

  await writeGeneratedFile(
    'weapon-aliases.ts',
    `${toTsConst('GENERATED_WEAPON_ALIASES', generatedWeaponAliases)}
export type GeneratedWeaponType = keyof typeof GENERATED_WEAPON_ALIASES;
`,
  );
  await writeGeneratedFile(
    'location-aliases.ts',
    `${toTsConst('GENERATED_LOCATION_ALIASES', generatedLocationAliases)}
`,
  );
  await writeGeneratedFile(
    'phrase-intents.ts',
    `${toTsConst('GENERATED_PHRASE_INTENTS', phraseIntents)}
`,
  );
  await writeGeneratedFile(
    'ambiguity.ts',
    `${toTsConst('GENERATED_AMBIGUOUS_TERMS', ambiguousTerms)}
${toTsConst('GENERATED_PRIORITY_HOTSPOTS', priorityHotspots)}
`,
  );

  const warningsBody =
    warnings.length > 0
      ? `\nWarnings:\n- ${warnings.join('\n- ')}`
      : '';
  await writeGeneratedFile(
    'meta.ts',
    `export const GENERATED_LEXICON_META = {
  source: ${JSON.stringify(path.relative(REPO_ROOT, LEXICON_PATH))},
  minConfidence: ${MIN_CONFIDENCE},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  warningCount: ${warnings.length},
} as const;
`,
  );

  process.stdout.write(`Generated lexicon artifacts in ${path.relative(REPO_ROOT, GENERATED_DIR)}${warningsBody}\n`);
}

run().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
